name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn
      - run: yarn lint
      - run: yarn test:ci
      - name: cypress run
        uses: cypress-io/github-action@v4
        with:
          env: NEXT_PUBLIC_FIREBASE_CONFIG=${{ secrets.FIREBASE_CONFIG }}}
          build: yarn build
          start: yarn start
          browser: chrome
          spec: cypress/e2e/travel-all-pages.cy.ts
          wait-on: 'http://127.0.0.1:3000'
          wait-on-timeout: 300
      - name: upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress E2E Videos
          path: cypress/videos
