name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn
      - run: yarn lint
      - run: yarn test:ci
      - name: cypress run
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn start
          browser: chrome
          headless: true
          record: false
          wait-on: 'http://127.0.0.1:3000'
          wait-on-timeout: 300
