name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn
      - run: yarn test:ci
      - name: build
        run: yarn build
        env:
          NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      - name: cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          browser: chrome
          spec: cypress/e2e/travel-all-pages.cy.ts
          wait-on: 'http://127.0.0.1:3000'
          wait-on-timeout: 3000
      - name: upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress E2E Videos
          path: cypress/videos
